export const C = {
  ADD_POSTS: "ADD_POSTS",
  ADD_POST: "ADD_POST",
  SELECTED_USER: "SELECTED_USER",
  SET_TICKS: "SET_TICKS",
  GET_POST: "GET_POST",
  ADD_COMMENT: "ADD_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
  ADD_COMMENTS: "ADD_COMMENTS",
  ADD_RECENT_POSTS: "ADD_RECENT_POSTS",
  EDITED_COMMENT: "EDITED_COMMENT",
  RESOLVE_ISSUE: "RESOLVE_ISSUE",
  RECENT_CLICKED: "RECENT_CLICKED",
};
