export const C = {
  ADD_ISSUES: "ADD_ISSUES",
  DELETE_ISSUES: "DELETE_ISSUES",
  ADD_ISSUE: "ADD_ISSUE",
  ADD_SELECTED: "ADD_SELECTED",
  REMOVE_SELECTED: "REMOVE_SELECTED",
  ADD_FETCHED: "ADD_FETCHED",
  REMOVE_FETCHED: "REMOVE_FETCHED",
  DEPT_ISSUES: "DEPT_ISSUES",
  RESET_ISSUES: "RESET_ISSUES",
};
