export const C = {
  ADD_USERS: "ADD_USERS",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
  SELECTED_USER: "SELECTED_USER",
  UNSELECTED_USER: "UNSELECTED_USER",
  ADD_SELECTED_USERS: "ADD_SELECTED_USERS",
  DELETE_SELECTED_USERS: "DELETE_SELECTED_USERS",
  RESET_SELECTED_USERS: "RESET_SELECTED_USERS",
  USER_DEPTS: "USER_DEPT",
  USER_STATS: "USER_STATS",
  SECTION_USERS: "SECTION_USERS",
  SEARCHED_USERS: "SEARCHED_USERS",
};
