export const C = {
  ADD_DEPARTMENT: "ADD_DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  EDIT_DEPARTMENT: "EDIT_DEPARTMENT",
  ADD_DEPARTMENTS: "ADD_DEPARTMENTS",
  ADD_USERS: "ADD_USERS",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",
};
